const A2AEndpoints = {
  login: { url: "/login", method: "POST" },
  logout: { url: "/logout", method: "DELETE" },
  signup: { url: "/signup", method: "POST" },
  createUserProfile: { url: "/signup-user", method: "POST" },
  searchChild: { url: "/search-child", method: "POST" },
  createParentProfile: { url: "/signup-parent", method: "POST" },
  deleteAccount: { url: "/delete-account", method: "DELETE" },
  userProfile: { url: "/user_profile", method: "GET" },
  updateUserProfile: { url: "/user_profile/edit", method: "PUT" },
  updateUserAvatar: { url: "/user_profile/avatar", method: "PUT" },
  matchmakingCategories: { url: "/matchmaking_categories", method: "GET" },
  matchmakingQuestions: { url: "/questions", method: "GET" },
  categoryQuestions: { url: "/questions/matchmaking_category/", method: "GET" },
  piechartPercentages: { url: "/category_percentages", method: "GET" },
  savePiechartPercentages: { url: "/category_percentages", method: "POST" },
  match: { url: "/match", method: "POST" },
  userResponses: { url: "/my_question_answers", method: "GET" },
  matchResponses: { url: "/match_question_answers", method: "GET" },
  viewChild: { url: "/view-child", method: "GET" },
  toggleResponseVisibility: { url: "/toggle_question/", method: "PUT" },
  getMatchProfile: { url: "/match_profiles/", method: "GET" },
  filterMatches: { url: "/search-matches", method: "POST" },
  parentsStarred: { url: "/starred_match_profiles", method: "GET" },
  starProfile: { url: "/starred_match_profiles", method: "POST" },
  unstarProfile: { url: "/starred_match_profiles/delete", method: "DELETE" },
  userFavorites: { url: "/favourited_match_profiles", method: "GET" },
  favoriteProfile: { url: "/favourited_match_profiles", method: "POST" },
  unfavoriteProfile: {
    url: "/favourited_match_profiles/delete",
    method: "DELETE",
  },
};

export default A2AEndpoints;
